gcc -o ~/tags/addTags ~/tags/addTags.c
gcc -o ~/tags/mkTags ~/tags/mkTags.c
gcc -o ~/tags/dropTags ~/tags/dropTags.c
gcc -o ~/tags/rmTags ~/tags/rmTags.c
gcc -o ~/tags/lsFile ~/tags/lsFile.c
gcc -o ~/tags/lsFic ~/tags/lsFic.c
gcc -o ~/tags/lsTags ~/tags/lsTags.c
gcc -o ~/tags/mv ~/tags/mv.c
gcc -o ~/tags/cp ~/tags/cp.c
